github.com:
    users:
        LLAMA9144:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: LLAMA9144
